name: fintech
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.1+2

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  either_dart: ^1.0.0
  connectivity_plus: ^6.0.5
  http: ^1.2.2
  share_plus: ^7.0.2

  http_interceptor: ^2.0.0
  url_launcher: ^6.3.1
  get: ^4.6.6
  flutter_html: ^3.0.0
  qr_code_scanner_plus: ^2.0.10+1
  qr_code_tools: ^0.1.0
  qr_flutter: ^4.1.0
  dio: ^5.3.3
  open_filex: ^4.3.2
  file_picker: ^8.1.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  metamap_plugin_flutter: ^4.4.12
  timeago: ^3.7.0
  bounce: ^1.0.2
  cached_network_image: ^3.4.1
  dropdown_button2: ^2.3.9
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  country_code_picker: ^3.0.0
  carousel_slider: ^5.0.0
  country_picker: ^2.0.26
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1
  encrypt: ^5.0.3
  image_picker: ^1.1.2
  path_provider: ^2.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/gif/
    - assets/images/main_image/
    - assets/images/extra_image/
    - assets/images/svg_image/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-ThinItalic.ttf
        - asset: assets/fonts/DMSans_18pt-Black.ttf
        - asset: assets/fonts/DMSans_18pt-BlackItalic.ttf
        - asset: assets/fonts/DMSans_18pt-Bold.ttf
        - asset: assets/fonts/DMSans_18pt-BoldItalic.ttf
        - asset: assets/fonts/DMSans_18pt-ExtraBold.ttf
        - asset: assets/fonts/DMSans_18pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/DMSans_18pt-Italic.ttf
        - asset: assets/fonts/DMSans_18pt-Medium.ttf
        - asset: assets/fonts/DMSans_18pt-MediumItalic.ttf
        - asset: assets/fonts/DMSans_18pt-Regular.ttf
        - asset: assets/fonts/DMSans_18pt-SemiBold.ttf
        - asset: assets/fonts/DMSans_18pt-ThinItalic.ttf
        - asset: assets/fonts/DMSans_24pt-Black.ttf
        - asset: assets/fonts/DMSans_24pt-BlackItalic.ttf
        - asset: assets/fonts/DMSans_24pt-Bold.ttf
        - asset: assets/fonts/DMSans_24pt-BoldItalic.ttf
        - asset: assets/fonts/DMSans_24pt-ExtraBold.ttf
        - asset: assets/fonts/DMSans_24pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/DMSans_24pt-ExtraLightItalic.ttf
        - asset: assets/fonts/DMSans_24pt-Italic.ttf
        - asset: assets/fonts/DMSans_24pt-Light.ttf
        - asset: assets/fonts/DMSans_24pt-LightItalic.ttf
        - asset: assets/fonts/DMSans_24pt-Medium.ttf
        - asset: assets/fonts/DMSans_24pt-MediumItalic.ttf
        - asset: assets/fonts/DMSans_24pt-Regular.ttf
        - asset: assets/fonts/DMSans_24pt-SemiBold.ttf
        - asset: assets/fonts/DMSans_24pt-SemiBoldItalic.ttf
        - asset: assets/fonts/DMSans_24pt-Thin.ttf
        - asset: assets/fonts/DMSans_24pt-ThinItalic.ttf
        - asset: assets/fonts/DMSans_36pt-Black.ttf
        - asset: assets/fonts/DMSans_36pt-BlackItalic.ttf
        - asset: assets/fonts/DMSans_36pt-Bold.ttf
        - asset: assets/fonts/DMSans_36pt-BoldItalic.ttf
        - asset: assets/fonts/DMSans_36pt-ExtraBold.ttf
        - asset: assets/fonts/DMSans_36pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/DMSans_36pt-ExtraLight.ttf
        - asset: assets/fonts/DMSans_36pt-ExtraLightItalic.ttf
        - asset: assets/fonts/DMSans_36pt-Italic.ttf
        - asset: assets/fonts/DMSans_36pt-Light.ttf
        - asset: assets/fonts/DMSans_36pt-LightItalic.ttf
        - asset: assets/fonts/DMSans_36pt-Medium.ttf
        - asset: assets/fonts/DMSans_36pt-MediumItalic.ttf
        - asset: assets/fonts/DMSans_36pt-Regular.ttf
        - asset: assets/fonts/DMSans_36pt-SemiBold.ttf
        - asset: assets/fonts/DMSans_36pt-SemiBoldItalic.ttf
        - asset: assets/fonts/DMSans_36pt-Thin.ttf
        - asset: assets/fonts/DMSans_36pt-ThinItalic.ttf
        - asset: assets/fonts/DMSans-Black.ttf
        - asset: assets/fonts/DMSans-BlackItalic.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-BoldItalic.ttf
        - asset: assets/fonts/DMSans-ExtraBold.ttf
        - asset: assets/fonts/DMSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/DMSans-ExtraLight.ttf
        - asset: assets/fonts/DMSans-ExtraLightItalic.ttf
        - asset: assets/fonts/DMSans-Italic.ttf
        - asset: assets/fonts/DMSans-Light.ttf
        - asset: assets/fonts/DMSans-LightItalic.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-MediumItalic.ttf
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-SemiBold.ttf
        - asset: assets/fonts/DMSans-SemiBoldItalic.ttf
        - asset: assets/fonts/DMSans-Thin.ttf
        - asset: assets/fonts/DMSans-ThinItalic.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
